<?php
define("_INSTALL_WEBMASTER", "Administração"); 
define("_INSTALL_WEBMASTERD", "Grupo dos principais administradores deste portal."); 
define("_INSTALL_REGUSERS", "Associados"); 
define("_INSTALL_REGUSERSD", "Grupo de visitantes cadastrados"); 
define("_INSTALL_ANONUSERS", "Anônimos"); 
define("_INSTALL_ANONUSERSD", "Grupo de visitantes anônimos");
define("_INSTALL_ANON", "Anônimo"); 
define("_INSTALL_DISCLMR", "Apesar dos administradores e moderadores deste portal tentarem remover ou editar todo o conteúdo questionável o mais depressa possível, será impossível rever todas as mensagens antes de serem publicadas. Desta forma, tome conhecimento de que todas as mensagens publicadas neste site são de responsabilidade de seus respectivos autores. Não sendo os administradores e moderadores responsáveis pelo seu conteúdo. Você compromete-se a não publicar conteúdo abusivo, obsceno, vulgar, difamatório, ameaçador, sexual, ódio ou qualquer conteúdo que viole as leis vigentes. Se o fizer, corre o risco de ser permanentenmente banido do site (com uma notificação feita ao seu fornecedor de acesso à Internet). O número IP de todas as mensagens publicadas é guardado para ajudar a implementar estas normas. Criar várias contas para um único associado é proibido. Você concorda que o administrador ou moderador tem o direito de remover, editar, mover ou fechar qualquer tópico que ele ache próprio. Como associado, concorda que qualquer informação introduzida no site será guadada em um banco de dados. Apesar dessa informação não ser distribuída a terceiros sem o seu consentimento, os administradores não podem ser responsabilizados por qualquer ataque informático que comprometa esses dados. Este site usa cookies para guardar informação em seu computador, os <i>cookies</i> não contêm nenhuma informação introduzida por si, são usados apenas para melhorar a qualidade de sua estadia no site. O seu endereço de e-mail é apenas usado para confirmar a sua senha (e no caso de se esquecer dela). Ao prosseguir, você estará concordando com este termo de responsabilidade."); 
?>
