<?php
define('XOOPS_COMMENT_APPROVENONE', 0);
define('XOOPS_COMMENT_APPROVEALL', 1);
define('XOOPS_COMMENT_APPROVEUSER', 2);
define('XOOPS_COMMENT_APPROVEADMIN', 3);
define('XOOPS_COMMENT_PENDING', 1);
define('XOOPS_COMMENT_ACTIVE', 2);
define('XOOPS_COMMENT_HIDDEN', 3);
define('XOOPS_COMMENT_OLD1ST', 0);
define('XOOPS_COMMENT_NEW1ST', 1);
?>
